### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by bbkr** [bbkr/EmailDKIM#1]
- [ ] Research which RSA library can be used. Or write own mini-wrapper.
- [ ] Header simple canonicalization.
- [ ] Header relaxed canonicalization. Check how Email::MIME implements header folding.
- [ ] Body simple canonicalization.
- [ ] Body relaxed canonicalization. Check if Quoted Printable is binary endoced (including newlines).
- [ ] Signer interface. List of headers to choose (default to list from 5.4.1). RSA version (do we bother with RSA1 in signer?). RSA key. Canonicalization algorithms. Selector. Domain. Identity (default none). Notes (optional).
